### ISSUE TITLE
Add the ioctls used by CrosVM

### ISSUE THREAD

**Issue by andreeaflorescu** [rust-vmm/kvm#11]
To be scoped.

**Comment by MrXinWang** [comment]
Hi @andreeaflorescu ! 

For **aarch64** platform, there are currently 6 ioctls in CrosVM which are not included in rust-vmm, namely:

- `KVM_IRQ_LINE`

- `KVM_SET_SIGNAL_MASK`

- `KVM_SET_MEMORY_REGION`

- `KVM_HAS_DEVICE_ATTR`

- `KVM_SET_GUEST_DEBUG`

- `KVM_GET_REG_LIST`

Among these 6 ioctls, only the first two ioctls (`KVM_IRQ_LINE` and `KVM_SET_SIGNAL_MASK`) have some implemented functions to call them, respectively in [`/crosvm/kvm/src/lib.rs#744`](https://chromium.googlesource.com/chromiumos/platform/crosvm/+/refs/heads/master/kvm/src/lib.rs#744) and [`/crosvm/kvm/src/lib.rs#1628`](https://chromium.googlesource.com/chromiumos/platform/crosvm/+/refs/heads/master/kvm/src/lib.rs#1628). The other 4 ioctls are only declared but not implemented in [`/crosvm/kvm_sys/src/lib.rs`](https://chromium.googlesource.com/chromiumos/platform/crosvm/+/refs/heads/master/kvm_sys/src/lib.rs)

Wondering if we can add these ioctls for rust-vmm, if so, we @michael2012z will create some PRs to do that. Thanks!

**Comment by andreeaflorescu** [comment]
We never planned for kvm-ioctls to have all the supported ioctls. I think it make sense to add ioctls as they're needed. So I would start with the ones used by CrosVM and we can continue from there. What do you think?

**Comment by MrXinWang** [comment]
Hi @andreeaflorescu , thanks very much for the suggestion! Created a PR for the ioctl `KVM_IRQ_LINE` already, and I think my colleague will take care of the other one. Thanks.

**Comment by andreeaflorescu** [comment]
Closing this as we are adding ioctls on an as-needed basis.
