### ISSUE TITLE
Remove Kvm::new_with_fd_number function

### ISSUE THREAD

**Issue by andreeaflorescu** [rust-vmm/kvm#115]
This function is not needed as we already implement `FromRawFd` for `Kvm`.
When deleting it, we should also move the documentation of `new_with_fd_number` to the `from_raw_fd` function.

The implementation of `Kvm::new` needs to be adapted as it was using the `new_with_fd_number` function.

**Comment by smortime** [comment]
👋 I'll take this issue if no one else has started

**Comment by andreeaflorescu** [comment]
@smortime I've assigned the issue to you. Lemme know if you need help with anything.
