### ISSUE TITLE
use u64 for specifying the id of the vcpu

### ISSUE THREAD

**Issue by andreeaflorescu** [rust-vmm/kvm#123]
Right now the `create_vcpu` function expects an u8, but KVM ioctl expects u64 here. We can update this number to match the KVM API.

**Comment by gabhijit** [comment]
I think this is quite simple. Simply changing the parameter type should be good enough. No new test cases are required to be added. Right? As discussed on the other issue above - changing it to `u32` is fine? Although I think `u16` should be good enough for foreseeable future :-) 

Edit: `u16` will be borderline suffice. For powerpc `KVM_MAX_VCPU_ID` can be up to 65536. [reference](https://elixir.bootlin.com/linux/latest/source/arch/powerpc/include/asm/kvm_host.h#L37). So may be `u32` is a good idea.

**Comment by andreeaflorescu** [comment]
@gabhijit I think u64 would be better so we match the KVM the `KVM_CREATE_VCPU` takes a ulong as a parameter, and so it seems the safest way to ensure we're compatible with other architectures or future enhancements.

**Comment by gabhijit** [comment]
Okay. Should I submit a PR with this? Also, I think it'll be a good idea to add a test case where a number is a valid `u64` number but greater than `MAX_KVM_CPU_ID` and make sure that we get `EINVAL` errno set.

**Comment by andreeaflorescu** [comment]
@gabhijit yap, sounds good.

**Comment by andreeaflorescu** [comment]
Fixed by https://github.com/rust-vmm/kvm-ioctls/commit/4f61bba6236afff7beaece632e921a5428ff680d
