### ISSUE TITLE
Request for 0.6.1 release with locked dependencies.

### ISSUE THREAD

**Issue by jschwe** [rust-vmm/kvm#141]
Hi,

The latest `vmm-sys-util` update has broken our downstream build of uhyve, since `kvm-ioctls` 0.6 is not compatible with the newest version ( `vmm-sys-util` 0.8), but specifies its dependencies as `>=`.  Could you push a 0.6.1 release with `vmm-sys-util` bound to version 0.7?
This would give us some time to update the dependencies on our side.

**Comment by jiangliu** [comment]
Seems it's the first time facing such a situation, need to figure a way to create branches and publish v0.6.1.

**Comment by andreeaflorescu** [comment]
We've been doing branch releases for security vulnerabilities in the past, and we can use the same approach (for example the patch releases for vm-memory v0.1.1, v0.1.2, v0.2.1, and v0.2.2). We can provide a patch release for v0.6.0.

**Comment by alxiord** [comment]
This will have to pull in a similar patch release for `kvm-bindings`, otherwise `kvm-bindings` will pull in the newest `vmm-sys-util` and cause a dependency conflict.

**Comment by alxiord** [comment]
v0.6.1 released: https://github.com/rust-vmm/kvm-ioctls/releases/tag/v0.6.1 and https://crates.io/crates/kvm-ioctls/0.6.1
