### ISSUE TITLE
Test case get/set_cpuid() fails with the CI system

### ISSUE THREAD

**Issue by jiangliu** [rust-vmm/kvm#152]
The test_get_cpuid()/test_set_cpuid() test cases fail with the CI system. It seems the failure is caused by latest Linux kernel, it works with 4.19 linux kernel. Error messages:

---- ioctls::vcpu::tests::test_get_cpuid stdout ----
--
&nbsp; | thread 'ioctls::vcpu::tests::test_get_cpuid' panicked at 'assertion failed: `(left == right)`
&nbsp; | left: `[kvm_cpuid_entry2 { function: 0, index: 0, flags: 0, eax: 22, ebx: 1970169159, ecx: 1818588270, edx: 1231384169, padding: [0, 0, 0] }, kvm_cpuid_entry2 { function: 1, index: 0, flags: 0, eax: 329303, ebx: 339740672, ecx: 1996141091, edx: 260832255, padding: [0, 0, 0] }, kvm_cpuid_entry2 { function: 2, index: 0, flags: 0, eax: 1979933441, ebx: 15775231, ecx: 0, edx: 12779520, padding: [0, 0, 0] }]`,
&nbsp; | right: `[kvm_cpuid_entry2 { function: 1931872256, index: 4294942226, flags: 0, eax: 4294950912, ebx: 46, ecx: 0, edx: 1931498368, padding: [4294942226, 0, 0] }, kvm_cpuid_entry2 { function: 0, index: 0, flags: 0, eax: 0, ebx: 0, ecx: 0, edx: 0, padding: [0, 0, 0] }, kvm_cpuid_entry2 { function: 0, index: 0, flags: 0, eax: 0, ebx: 0, ecx: 0, edx: 0, padding: [0, 0, 0] }]`', src/ioctls/vcpu.rs:1475:17
&nbsp; | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
&nbsp; | &nbsp;
&nbsp; | ---- ioctls::vcpu::tests::test_set_cpuid stdout ----
&nbsp; | thread 'ioctls::vcpu::tests::test_set_cpuid' panicked at 'assertion failed: `(left == right)`
&nbsp; | left: `0`,
&nbsp; | right: `1263359563`', src/ioctls/vcpu.rs:1543:21
&nbsp; | &nbsp;

According to the log messages, it seems that vcpu.set_cpuid2() doesn't work as expected.

**Comment by alxiord** [comment]
Hasn't happened since CI was updated to kernel 5.10 - see https://github.com/rust-vmm/kvm-ioctls/pull/153#issuecomment-866792493 . Closing.
