### ISSUE TITLE
Correctly expose CpuId related items

### ISSUE THREAD

**Issue by dianpopa** [rust-vmm/kvm#16]
There are 2 issues identified here:
* `MAX_KVM_CPUID_ENTRIES` is a x86_64 specific constant and should be labeled as such.
* We also need to publicly expose `CpuId` wrapper since it needs to be accessible from outside.

**Comment by andreeaflorescu** [comment]
We also need `KvmRunWrapper` and `Result`.
@sameo is partially working on this.

**Comment by andreeaflorescu** [comment]
Just notice that #14 already mentions these issues. @dianpopa can you update it to only mention the `MAX_KVM_CPUID_ENTRIES` issue?

**Comment by acatangiu** [comment]
Fixed by #64 

This crate no longer exports `MAX_KVM_CPUID_ENTRIES`.
`KVM_MAX_CPUID_ENTRIES` is defined and exported by the `kvm-bindings` crate only on `x86_64`.
