### ISSUE TITLE
Expose `kvm_run::__bindgen_anon_1::debug`

### ISSUE THREAD

**Issue by mkroening** [rust-vmm/kvm#162]
The KVM docs say, “If the exit_reason is KVM_EXIT_DEBUG, then a vcpu is processing a debug event for which architecture specific information is returned” ([The Definitive KVM (Kernel-based Virtual Machine) API Documentation — The Linux Kernel documentation](https://www.kernel.org/doc/html/latest/virt/kvm/api.html#the-kvm-run-structure)).

I'd like to access that field on `KVM_EXIT_DEBUG`. While I could remap the `kvm_run` structure myself, it would be nicer to use the already mapped `VcpuFd::kvm_run_ptr` instead. We could add `VcpuFd::get_kvm_run(&self) -> &mut kvm_run` to allow broad access to `kvm_run` or return it from `VcpuFd::run()` with `VcpuExit::Debug(&'a kvm_bindings::kvm_run__bindgen_ty_1__bindgen_ty_5)`.

What do you think?

**Comment by andreeaflorescu** [comment]
I think it would be better to return it from `VcpuFd::run`. Would you like to propose a PR?

**Comment by mkroening** [comment]
Yeah, I'll prepare a PR. :+1:
