### ISSUE TITLE
Missing examples for Result and KvmRunWrapper

### ISSUE THREAD

**Issue by sameo** [rust-vmm/kvm#17]
PR #15 adds some dummy code examples for testing the scope of the `KvmRunWrapper` and `Result` structures.

Adding more relevant examples would allow for actually testing the structure methods and their scope as well.

**Comment by andreeaflorescu** [comment]
`Result` is no longer exported by this crate. Finding a useful example with `KvmRunWrapper` proved to be difficult. Closing this.
