### ISSUE TITLE
Add KVM_CAP_ARM_PMU_V3 in cap.rs

### ISSUE THREAD

**Issue by xuejun-xj** [rust-vmm/kvm#215]
KVM_CAP_ARM_PMU_V3 is used to check whether KVM supports PMUv3. This is a precheck before setting PMU attributes for vcpu.

**Comment by alyssais** [comment]
I didn't notice that this issue existed when I did it, but this was fixed by https://github.com/rust-vmm/kvm-ioctls/commit/23a3bb045a467e60bb00328a0b13cea13b5815d0.

**Comment by xuejun-xj** [comment]
> I didn't notice that this issue existed when I did it, but this was fixed by [23a3bb0](https://github.com/rust-vmm/kvm-ioctls/commit/23a3bb045a467e60bb00328a0b13cea13b5815d0).

Ok, I see that. Thanks! @alyssais
