### ISSUE TITLE
Any plans for new release

### ISSUE THREAD

**Issue by jinankjain** [rust-vmm/kvm#249]
Since the last release was in Aug is there any plan to do a new release?

**Comment by andreeaflorescu** [comment]
@jinankjain do you mind opening a PR preparing the release? We have releases on demand, so that's why you haven't seen one since august.

**Comment by andreeaflorescu** [comment]
Otherwise I recommend writing on the slack channel to see if any maintainer can help you with that.

**Comment by jinankjain** [comment]
@andreeaflorescu I created a PR to bump the version https://github.com/rust-vmm/kvm-ioctls/pull/250.
