### ISSUE TITLE
Add unit test for `set_cpuid2`

### ISSUE THREAD

**Issue by andreeaflorescu** [rust-vmm/kvm#28]
We have no unit test for testing the `set_cpuid2` method. Right now it is tested with the code example but that's not an ideal state.

**Comment by wey-gu** [comment]
Hi, I'd like to look into this and help ASAP in my free time.
The `good first issue` label is very eye-catching to me :-), thanks.

**Comment by andreeaflorescu** [comment]
@wey-gu cool! Let me know if you need help with anything.
