### ISSUE TITLE
Add proper tests for register/unregister irqfd on aarch64

### ISSUE THREAD

**Issue by andreeaflorescu** [rust-vmm/kvm#67]
Both the unit tests and the example only test the error cases on aarch64. We should add proper unit tests for these functions where the operations are successful & examples that actually call the functions.

**Comment by MrXinWang** [comment]
Will propose a PR to address this soon.

**Comment by andreeaflorescu** [comment]
Fixed by: https://github.com/rust-vmm/kvm-ioctls/pull/74
