### ISSUE TITLE
ARM Support

### ISSUE THREAD

**Issue by andreeaflorescu** [rust-vmm/kvm#8]
Currently kvm-ioctls only has support for x86_64.
- [x] Setup CI for ARM
- [ ] Add ARM specific coverage test #9 
- [x] Add ARM specific ioclts
- [ ] Add unit tests for ARM
- [x] Add `run_code` example with ARM

**Comment by rhdrjones** [comment]
> Currently kvm-ioctls only has support for x86_64.
> 
>     * [x]  Setup CI for ARM
> 
>     * [ ]  Add ARM specific coverage test #9
> 
>     * [x]  Add ARM specific ioclts
> 
>     * [ ]  Add unit tests for ARM
> 
>     * [ ]  Add `run_code` example with ARM

I'll take a look at these missing bullets in the reverse order they're listed, i.e. starting with the run_code example.

**Comment by michael2012z** [comment]
`KVM_GET_VCPU_EVENTS` and `KVM_SET_VCPU_EVENTS` are restricted to x86 new, but they became enabled on aarch64 in recent versions of kernel.
Any good practice to handle such kernel-version-sensitive ioctls?

**Comment by andreeaflorescu** [comment]
@michael2012z we currently use the v4.20 bindings. So probably we want to have the ioctls that are available in 4.20. We didn't discuss about adding bindings to newer kernel versions. I think we can send an email to rust-vmm to see what other people think about this. I don't really have strong preferences here. If the ioctls available in newer versions have associated caps that we can check before calling them, it should be okay to add them directly. Otherwise we might want to use rust features to disable them by default.

**Comment by rhdrjones** [comment]
Typically caps are also added or enabled with new API. When KVM_GET_VCPU_EVENTS and KVM_SET_VCPU_EVENTS were introduced to arm KVM_CAP_VCPU_EVENTS was enabled. As Andreea says, rust-vmm should check caps whenever possible before using their associated features.

**Comment by michael2012z** [comment]
@andreeaflorescu @rhdrjones Thanks. 
Checking caps is a good idea. We can use `check_extension()` defined in `system.rs` to check caps before calling the ioctl. 
I created PR https://github.com/rust-vmm/kvm-ioctls/pull/73 for it.

**Comment by andreeaflorescu** [comment]
Arm support is already added to kvm-ioctls. There are a still improvements needed (such as on the documentation), but these are tracked in separate issues.
