### ISSUE TITLE
Add the support for KVM_HAS_DEVICE_ATTR

### ISSUE THREAD

**Issue by michael2012z** [rust-vmm/kvm#88]
The issue we are trouble-shooting in https://github.com/rust-vmm/kvm-ioctls/pull/87 reminded me that we may need to add the support for `KVM_HAS_DEVICE_ATTR` ioctl.

`KVM_HAS_DEVICE_ATTR` is used to check whether a device supports a particular attribute.

A hypervisor can choose to check it before calling `KVM_SET_DEVICE_ATTR`, this way the code may look more graceful. See an example in kvmtool: https://github.com/michael2012z/kvmtool/blob/master/arm/gic.c#L324

**Comment by crab2313** [comment]
Anyone working on this? It is required to implement GICv2 interrupt controller on ARM64 KVM.I will work on this if nobody assigned to the issue.

**Comment by michael2012z** [comment]
Thank you. But a PR is almost ready, I will post as soon as possible.

**Comment by crab2313** [comment]
@michael2012z Thank you. By the way I have proposed another implementation of ARM64 PE Image format support for linux-loader. I will make a pull request once I confirmed it is working on cloud-hypervisor.

**Comment by michael2012z** [comment]
Great to know that. My previous PR against PE kernel loading was not complete, I can't upload binary to finish the test (company policy).
