### ISSUE TITLE
ARM coverage test case `test_create_device` failure on some machines with gnu toolchain

### ISSUE THREAD

**Issue by MrXinWang** [rust-vmm/kvm#89]
Referencing discussion in PR #87, ARM coverage test case `test_create_device` will fail on some machines with gnu toolchain. This failure is caused by the assertion in arm `test_create_device` case:
`assert_eq(errno::Error::last().errno(), 25);` 
as ioctl `device_fd.set_device_attr(&dist_attr)` returns `EINVAL` instead of `ENOTTY`.

Note that this bug is only reproducible in only some of the arm64 machines, and using musl toolchain also will not lead to this problem. Root cause of this bug needs to be investigated and fixed.

**Comment by aw** [comment]
Hello,

I believe `VGIC_V3` requires an _online_ vCPU prior to setting device attributes, [see here](https://www.kernel.org/doc/html/latest/virt/kvm/devices/arm-vgic-v3.html).

Add this before `set_device_attr` assert in [src/ioctls/device.rs#L290](https://github.com/rust-vmm/kvm-ioctls/blob/master/src/ioctls/device.rs#L290):

```
vm.create_vcpu(0).unwrap();
```

Tested successfully on an arm64 device, with _musl_ and _libc_. Hope this helps.

/cc @andreeaflorescu

**Comment by andreeaflorescu** [comment]
Thanks for looking into this @aw! Do you want to contribute the required change as well? Or should we open a PR with it?

**Comment by aw** [comment]
Sure I can make a PR.
