### ISSUE TITLE
Supporting `KVM_GET_DEVICE_ATTR` ioctl

### ISSUE THREAD

**Issue by MrXinWang** [rust-vmm/kvm#99]
Hi guys, I am wondering if we are missing supporting this `KVM_GET_DEVICE_ATTR` ioctl (doc see [here](https://github.com/torvalds/linux/blob/master/Documentation/virt/kvm/api.rst#480-kvm_set_device_attrkvm_get_device_attr)) or it is me understanding it incorrectly... Currently I can only find `KVM_SET_DEVICE_ATTR` and `KVM_HAS_DEVICE_ATTR` in master branch rust-vmm.

As far as I know, using this ioctl is the only way to extract the vGIC states on AArch64.

@andreeaflorescu @michael2012z could you please share any ideas?

**Comment by michael2012z** [comment]
I guess it's not something missed. It just hasn't been needed.

**Comment by dianpopa** [comment]
> I guess it's not something missed. It just hasn't been needed.

Indeed, it has not been needed until now. However, we would be happy to see this functionality in rust-vmm.

**Comment by MrXinWang** [comment]
@dianpopa PR #100 created to address this.
